#!/bin/sh
#=============================================================================
#
#             --- CAEN SpA - Computing Systems Division ---
#
#  Library installation script.
#
#
#  March  2004 :   Created.
#
#=============================================================================

search_dir=./x64
for file in "$search_dir"/*
do
  install  $file /usr/lib/
  filename="$(basename -- $file)"
  ln -sf /usr/lib/$filename /usr/lib/libCAENVME.so
done
/sbin/ldconfig
cp ../include/* /usr/include/
