#!/bin/sh
#=============================================================================
#
#             --- CAEN SpA - Computing Systems Division ---
#
#  Library installation script for arm64 systems.
#
#=============================================================================

if ! ldconfig -p | grep -q libusb-1.0
then
    echo >&2 "Error: libusb-1.0 is missing. Please install it and retry."
    exit 1
fi

search_dir=./arm64

for file in "$search_dir"/*
do
    install $file /usr/lib/
    filename="$(basename -- $file)"
    ln -sf /usr/lib/$filename /usr/lib/libCAENVME.so
done

# /usr/lib is missing from default ld.so search path on some distrubutions
echo "/usr/lib" >> /etc/ld.so.conf.d/caen-libraries.conf

/sbin/ldconfig

for file in ../include/*
do
    install -m 644 $file /usr/include/
done
